# Generated by Django 6.0.2 on 2026-02-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='group',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_description',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
